config/routes.rb
Rails.application.routes.draw do
  resources :books do
    collection { post :import }
  end

  resources :points
  resources :exams do
    collection { post :import }
  end

  resources :instructions do
    collection { post :import }
  end

  resources :tags do
    collection { post :import }
  end

  resources :appointments do
    collection { post :import }
  end

  resources :users do
    collection { post :import }
  end

  root 'home#index'
  
  get '/import', to: 'home#import'
  get '/export', to: 'home#export'

  get '/model_instruc', to: 'instructions#model'
  get '/model_exam', to: 'exams#model'


  get 'exams/export', to: 'exams#export'

  get 'instructions/export', to: 'instructions#export'
  
  get '/smart', to: 'exams#smart'
  get '/instructions/:search', to: 'instructions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  unless Rails.env.test?
    # http_basic_authenticate_with name: "skynet", password: "$kyn3T"
  end

  def index
    @tags = Tag.all.order(:id)
  end

  def import
  end

  def export
  end
end

app/views/home/_controls_menu.html.erb
<div class="controls">
  <ul>
    <% for i in 0..4 do %>
      <li>
      </li>
    <% end %>
  </ul>
</div>

app/views/home/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%# <title>skynet</title> %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="#000000" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src='http://threejs.org/build/three.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/tween.js/17.4.0/Tween.min.js'></script>
    <script src='/app/assets/javascripts/exams.js'></script>
    <script src='/app/assets/javascripts/discovery_framework.js'></script>

  </head>

  	<body class="<%= controller_name %> <%= action_name %>">
    <div class="header">
      <div class="back">
        <a class="back-img" href="/" alt="Voltar" title="Voltar"></a>
        <a class="" href="/" alt="Voltar" title="Voltar"></a>
      </div>
      <div class="navbar-logo">
				<%# <%= image_tag "cdb.png", class: 'logo' %>
        <%# <h2 class='logo'>skynet</h2> %>
			</div>
    </div>
    <div class="content">
        <%= yield %>
    </div>

    <div id="cursor">
      <div id="circle-big"></div>
      <div id="circle"></div>
    </div>

<a>link</a>
  </body>
</html>

app/views/home/export.erb
<div class="home-container">
<div class="import-block">
<%= form_tag(import_instructions_path, multipart: true, class: 'form-inline import-form', id: 'import-instruc-form') do %>
  <label id="import-label" class="btn custom-input-btn">
    <a href='/instructions.csv' style="float: left;" class="title">Exportar Preparos</a>
  </label>
<% end %>
</div>

<div class="import-block">
<%= form_tag(import_exams_path, multipart: true, class: 'form-inline import-form', id: 'import-exams-form') do %>
  <label id="import-label" class="btn custom-input-btn">
    <a href='/exams.csv' style="float: left;" class="title">Exportar Exames</a>
  </label>
<% end %>
</div>
</div>

app/views/home/import.html.erb
<div class="home-container">
<div class="import-block">
  <%= form_tag(import_instructions_path, multipart: true, class: 'form-inline import-form', id: 'import-instruc-form') do %>
    <label id="import-label" class="btn custom-input-btn title">
      <input id="imported-instructions" type="file" name="file" style="display:none" accept="*" multiple>        
      <i class="fa fa-cloud-upload"></i> Importar Preparos
    </label>
  <% end %>
  <%= form_tag(import_instructions_path, multipart: true, class: 'form-inline import-form', id: 'import-instruc-form') do %>
    <a href='/model_instruc' style="float: left;" class="import-model-link">baixar modelo_preparos.csv</a>
  <% end %>
</div>

  <br />
  <br />
<div class="import-block">
  <%= form_tag(import_exams_path, multipart: true, class: 'form-inline import-form', id: 'import-exams-form') do %>
    <label id="import-label" class="btn custom-input-btn title">
      <input id="imported-exams" type="file" name="file" style="display:none" accept="*" multiple>        
      <i class="fa fa-cloud-upload"></i> Importar Exames
    </label>
  <% end %>
  <%= form_tag(import_instructions_path, multipart: true, class: 'form-inline import-form', id: 'import-instruc-form') do %>
    <a href='/model_exam' style="float: left;" class="import-model-link">baixar modelo_exames.csv</a>
  <% end %>
</div>

<div class="import-block">
  <%= form_tag(import_tags_path, multipart: true, class: 'form-inline import-form', id: 'import-tags-form') do %>
    <label id="import-label" class="btn custom-input-btn title">
      <input id="imported-tags" type="file" name="file" style="display:none" accept="*" multiple>        
      <i class="fa fa-cloud-upload"></i> Importar Tags
    </label>
  <% end %>
  <%= form_tag(import_instructions_path, multipart: true, class: 'form-inline import-form', id: 'import-instruc-form') do %>
    <a href='/model_exam' style="float: left;" class="import-model-link">baixar modelo_exames.csv</a>
  <% end %>
</div>

<div class="import-block">
  <%= form_tag(import_books_path, multipart: true, class: 'form-inline import-form', id: 'import-books-form') do %>
    <label id="import-label" class="btn custom-input-btn title">
      <input id="imported-books" type="file" name="file" style="display:none" accept="*" multiple>        
      <i class="fa fa-cloud-upload"></i> Importar Livros
    </label>
  <% end %>
</div>

</div>

<script>
  $(document).on("turbolinks:load", function() {
    window.skynet.exams.import_init();
  });
</script>

app/views/home/index.html.erb
<div class="main-menu">
<br />
<br />
<br />
<br />
</div>

<div class="menu main-menu">
  <div class="left">

    <a class="" href="<%= appointments_path %>">
      <div class="btn-view">
        <%= embedded_svg "032-calendar.svg", class: 'pin-icon' %>
      </div>
    </a>
  </div>
  <div class="middle">
    <a class="" href="/import">
      <div class="btn-view">
        <%= embedded_svg "023-folder.svg", class: 'pin-icon' %>
      </div>
    </a>
  </div>
  <div class="right">
    <a class="" href="/tags">
      <div class="btn-view" href="/tags">
        <%= embedded_svg "010-user.svg", class: 'pin-icon' %>
      </div>
    </a>
  </div>
</div>

<div id="black-canvas"></div>
<div id="back-dot-grid"></div>
<div id="particles"></div>
<canvas id="voronoi"></canvas>
<canvas id="screenSystemElem"></canvas>
<canvas id="circular-menu"></canvas>
<canvas id="discovery"></canvas>
<canvas id="nodeCon"></canvas>
<canvas id="rain-meter"></canvas>

<canvas id="canvashover" width="200" height="200"></canvas>

<div id="main-content">
 
  <div class="header">
    <div class="box a">
      <div class="box-content"></div>
    </div>
  </div>
  <div class="container-box">
    <div class="box a">
      <div class="box-content"></div>
    </div>
    <div class="box a">
      <div class="box-content"></div>
    </div>
    <div class="box a">
      <div class="box-content"></div>
    </div>
    <div class="box a">
      <div class="box-content"></div>
    </div>
    <div class="box a">
      <div class="box-content"></div>
    </div>
    <div class="box a">
      <div class="box-content">
        <div class="log-list-container">
          <ul class="log-list">
            <% @tags.each_with_index do |tag, i| %>
              <% if tag.name? %>
                <% if list_item_opacity(i, @tags.size) == 1 %>
                  <li style="opacity: <%= list_item_opacity i, @tags.size %>" class="selected" id="<%= tag.id %>">
                <% else %>
                  <li style="opacity: <%= list_item_opacity i, @tags.size %>" id="<%= tag.id %>">
                <% end %>
                  <%= link_to 'x', tag, class: "btn-delete", method: :delete, data: { confirm: 'confirm data removal:' } %>
                  <%# <%= link_to "#" + i.to_s.encrypt + " : " + tag.name.encrypt, edit_tag_path(tag), class: "btn-edit" %>
                  <%= link_to tag.name, edit_tag_path(tag), class: "btn-edit", id: tag.id %>
                  <%# <%= link_to " : " + tag.description.encrypt, edit_tag_path(tag), class: "btn-edit" %>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="box a">
      <div class="box-content"></div>
    </div>
    <div class="box a">
      <div class="box-content"></div>
    </div>
    <div class="box a">
      <div class="box-content"></div>
    </div>
  </div>
</div>
<div class='grid-limits'>
  <canvas id='plusigns' class='plus-signs-grid'>
  </canvas>
</div>

<div class="grid-wrapper">
  <div class="grid">
    <div class="grid-item"></div>
    <div class="grid-item"></div>
    <div class="grid-item"></div>
    <div class="grid-item"></div>
    <div class="grid-item back-0"></div>
    <div class="grid-item"></div>
    <div class="grid-item"></div>
    <div class="grid-item"></div>
    <div class="grid-item"></div>
  </div>
</div>

<%= render 'controls_menu' %>

<script>
$(document).on("turbolinks:load", function() {
  window.skynet.exams.exams_init();  
  window.skynet.discovery.discovery_framework_init();
  window.skynet.porsche.porsche_wheel_init();
  var arr = [];
  var iterations = 0;
  var full_iterations = 0;
  var repeat = true;
});
</script>