config/routes.rb
Rails.application.routes.draw do
  resources :books do
    collection { post :import }
  end

  resources :points
  resources :exams do
    collection { post :import }
  end

  resources :instructions do
    collection { post :import }
  end

  resources :tags do
    collection { post :import }
  end

  resources :appointments do
    collection { post :import }
  end

  resources :users do
    collection { post :import }
  end

  root 'home#index'
  
  get '/import', to: 'home#import'
  get '/export', to: 'home#export'

  get '/model_instruc', to: 'instructions#model'
  get '/model_exam', to: 'exams#model'


  get 'exams/export', to: 'exams#export'

  get 'instructions/export', to: 'instructions#export'
  
  get '/smart', to: 'exams#smart'
  get '/instructions/:search', to: 'instructions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/exam.rb
class Exam < ApplicationRecord
    has_and_belongs_to_many :instructions

    def self.to_csv
        csv_header = %w{
            ID 
            Mnemônico 
            Nome
            Área
            Responsável_Presente
            Preparos
        }
    
        CSV.generate(headers: true) do |csv|
          csv << csv_header
    
          all.each do |exam|
            instructions = ""
            exam.instructions.map{ |i| i.id_at_alliar}.uniq.each do |instruc|
                instructions << instruc.to_s + "; "
            end

            csv << [exam.id_at_alliar, exam.short_name, exam.name,  exam.area, exam.requires_responsible, instructions]
          end
        end
    end

    def self.to_csv_model
        csv_header = %w{
            ID 
            Mnemônico 
            Nome 
            Área 
            Responsável_Presente
            Preparos
        }

        CSV.generate(headers: true) do |csv|
            csv << csv_header
        end
    end

    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
            exam_hash = row.to_hash
            exam = find_or_create_by!(name: row[2])
            exam.id_at_alliar = row[0]
            exam.short_name = row[1]
            exam.name = row[2]
            exam.area = row[3]
            exam.requires_responsible = row[4]
            exam.domain = 'cdb'

            12.times do |t|
                next if row[5+t] == "-"
                next if row[5+t].blank?
        
                Instruction.where(id_at_alliar: row[5 + t].split(";")).find_each do |inst|
                    exam.instructions << inst
                end
            end

            unless exam.name.blank?
                exam.save!
            end
        end
    end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:edit, :show, :update, :destroy]
  before_action :set_exam_by_id, only: [:edit]

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.reorder("name").map{ |e| [e.id, e] }.paginate(page: params[:page], per_page: 10)

    unless (params[:examslist].blank?)
      @exams_list = params[:examslist].split(',')
      @exams = Exam.all.select{ |exam| @exams_list.include?(exam[:short_name].downcase)}
      .map{ |e| [e.id, e] }
      .paginate(page: params[:page], per_page: 10)
    end

    unless (params[:search].blank?)
      @exams = Exam.all.where("unaccent(lower(name)) like unaccent(?)", "%#{params[:search].downcase}%")
      .map{ |e| [e.id, e] }
      .paginate(page: params[:page], per_page: 10)

      if @exams.length == 0
        @exams = Exam.all.where("lower(short_name) like ?", "%#{params[:search].downcase}%")
        .map{ |e| [e.id, e] }
        .paginate(page: params[:page], per_page: 10)
      end
    end

    respond_to do |format|
      format.html
      format.csv {
        @exams = Exam.all
        send_data @exams.to_csv, filename: "exams-#{Date.today}.csv" 
      }
    end

    
  end

  # GET /smart?examslist=atccra,atcveiap,elasfig
  def smart
    @exams = Exam.all

    unless (params[:examslist].blank?)
      @exams_list = params[:examslist].downcase.split(',')
      @exams = @exams.select{ |exam| @exams_list.include?(exam[:short_name].downcase)}

      @instructions = []

      @exams.each do |exam|
        exam.instructions.each do |instruc|
          unless @instructions.include? instruc
            if @instructions.length == 0
                @instructions.push(instruc)
            else
              if instruc.instruction_type == 12
                current_instruction = @instructions.select{ |item| item.instruction_type == 12}[0]

                if current_instruction.blank?
                  @instructions.push(instruc)
                else
                  if current_instruction.priority < instruc.priority
                    @instructions.delete(current_instruction)
                    @instructions.push(instruc)
                  end
                end
              else
                  @instructions.push(instruc)
              end
            end
          end
        end
      end
    end
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  def model
    @exams = Exam.all
    send_data @exams.to_csv_model, filename: "model_exames_#{Date.today}.csv"
  end

  # GET /instruction/1/edit
  def edit
    unless params[:delete_instruc_id].blank?
      instruc = Instruction.find(params[:delete_instruc_id])
      @exam.instructions.delete(instruc)
      @exam.save
      
      redirect_to edit_exam_path(@exam)
    end

    unless params[:insert_instruc_id].blank?
      instruc = Instruction.find(params[:insert_instruc_id])
      @exam.instructions.push(instruc)
      @exam.save
      
      redirect_to edit_exam_path(@exam)
    end

    unless params[:search].blank?
      @instructions = Instruction.where('lower(content) like ?',"%#{params[:search].downcase}%")
    end

  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    unless params[:search].blank?
      redirect_to controller: 'exams', action: 'edit', id: params[:id], search: params[:search]
    end
  end

  def import
    unless params[:file].blank?
      CSV.foreach(params[:file].path, headers: true) do |row|
        exam_hash = row.to_hash

        if exam_hash["Descricao"].blank?
          redirect_to exams_path, alert: "Não foi possível importar os exames. O arquivo não segue o modelo de importação."
          break
        end

        Exam.import(params[:file])
        redirect_to exams_path, success: "Os exames foram importados com sucesso!"
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find_by_short_name(params[:id].upcase)
    end

    def set_exam_by_id
      @exam = Exam.find(params[:id])
      @instructions = []
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:name, :area, :short_name, :requires_responsible)
    end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_form.html.erb
<%= form_with(model: exam, local: true) do |form| %>
  <% if exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% exam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br />
  <div class="exam-title">
    <div class="exam-name" name="name"><%= @exam.name.downcase %></div>
    <div class="area"> - <%= @exam.short_name %> - <%= @exam.area.downcase %></div>
    <div class="clear"></div>
  </div>
  <br />

  <%# <br />
  <div class="field"> %>
    <%# <%= form.check_box :requires_responsible %>
    <%# <span><b>Responsável deverá estar presente.</b></span> %>
    <%# <div class="clear"></div>
  </div>
  <br /> %>

  <h3 class="title">Preparos</h3>

  <% exam.instructions.each do |instruc| %>
    <div class="instruction-card">
      <div class="instruction-content">
        <%= instruc.content %>
      </div>
          <%= link_to 'x', edit_exam_path(:delete_instruc_id => instruc.id), class: "btn-close" %>
      <div class="clear"></div>
    </div>
  <% end %>
  <br />

  <h3 class="title">Adicionar preparos</h3>

  <div class="row align-items-center">
    <div class="col title">
      <div class="input-group search-box">
        <input id="search-input" name="search" class="form-control search-input" type="text" value="Tipo ou parte da descrição preparo" autocomplete="off"/>
        <%# <%= link_to '', edit_exam_path, id: "search-instruct", class: "input-group-textv search-icon" %>
        <%= form.submit("", :id => 'search-instruct', :class => 'input-group-textv search-icon') %>
      </div>
    </div>
  </div>
  <br />

  <% unless @instructions.blank? %>
    <% @instructions.each do |instruction| %>
      <div class="exam-card">
        <div class="exam-name">
          <%= instruction.content %>
        </div>
          <%= link_to '+', edit_exam_path(:insert_instruc_id => instruction.id), class: "btn-close" %>
        <div class="clear"></div>
      </div>
    <% end %>
  <% end %>

  <br />

  <%# <% if @instructions.blank? %> 
    <%# <div class="instruction-card instruction-card-actions"> %>
      <%# <%= link_to 'Novo Preparo', instructions_path(:exam_id => exam.id), id: "add-instruct" %> 
    <%# </div> %>
  <%# <% end %> 

  <div class="actions">
    <%= form.hidden_field :name %>
    <%= form.hidden_field :short_name %>
    <%= form.hidden_field :area %>
    <%= form.hidden_field :instructions %>
    <%# <%= form.submit("Salvar", :class => 'btn-action') %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<%= render 'form', exam: @exam %>

<script>
  $(document).on("turbolinks:load", function() {
    window.skynet.exams.exams_init();
  });
</script>

app/views/exams/import.html.erb
<%= form_tag(import_instructions_path, multipart: true, class: 'form-inline import-form', id: 'import-instruc-form') do %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <label id="import-label" class="btn custom-input-btn">
    <input id="imported-instructions" type="file" name="file" style="display:none" accept="*" multiple>        
    <i class="fa fa-cloud-upload"></i> Importar Preparos
  </label>
<% end %>

<%= form_tag(import_exams_path, multipart: true, class: 'form-inline import-form', id: 'import-exams-form') do %>
  <%# <div class="form-group">
    <%= link_to "Export CSV", exams_path(format: "csv"), class: 'btn btn-primary' %>
  <%# </div> %>
  <%# <div class="form-group"> %>
    <%# <%= file_field_tag :file, class: '', value: 'teste' %> 
  <%# </div> %>
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <%# <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> %>

  <label id="import-label" class="btn custom-input-btn">
    <input id="imported-exams" type="file" name="file" style="display:none" accept="*" multiple>        
    <i class="fa fa-cloud-upload"></i> Importar Exames
  </label>

  <%# <div class="form-group"> %>
    <%# <%= submit_tag "Importar Exames", class: 'btn btn-info btn-import' %>
  <%# </div> %>
<% end %>

<%= form_tag(import_tags_path, multipart: true, class: 'form-inline import-form', id: 'import-exams-form') do %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <label id="import-label" class="btn custom-input-btn">
    <input id="imported-exams" type="file" name="file" style="display:none" accept="*" multiple>        
    <i class="fa fa-cloud-upload"></i> Importar Tags
  </label>
<% end %>

<script>
  $(document).on("turbolinks:load", function() {
    window.skynet.exams.import_init();
  });
</script>

app/views/exams/index.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>

<h2 class="title">Exames</h2>

<%= form_tag(exams_path, method: :get, class: 'form-container', enforce_utf8: false) do %>
		<div class="row align-items-center">
			<div class="col title">
					<div class="input-group search-box">
            <input id="search-input" name="search" class="exam-card form-control search-input" type="text" value="Nome ou mnemônico" autocomplete="off"/>
						<input type=submit class="input-group-textv search-icon" value="" />
					</div>
        </div>
		</div>
	<% end %>

 <% @exams.each do |exam| %>
   <% unless exam[1].name.blank? %>
     <div class="exam-card">
       <div class="exam-name">
         <%= link_to exam[1].name.downcase, edit_exam_path(exam[1]) %> 
      </div>
       <div class="area">
        <%= exam[1].short_name %>
        | <%= exam[1].area.downcase %> 
      </div>
      <div class="clear"></div>
    </div>
   <% end %> 
 <% end %> 
<br />

<div class="pagination-container">
  <div class="digg_pagination">
    <%= will_paginate @exams, 
      :container => false,
      :previous_label => '', 
      :next_label => '', 
      :outer_window => 0, 
      :inner_window => 1 %>
  </div>
</div>

<div class="clear"></div>

<script>
$(document).on("turbolinks:load", function() {
  window.skynet.exams.exams_init();  
});
</script>

app/views/exams/new.html.erb
<h1>New Exam</h1>

<%= render 'form', exam: @exam %>

<%= link_to 'Back', exams_path %>

app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exam.name %>
</p>

<p>
  <strong>Area:</strong>
  <%= @exam.area %>
</p>

<p>
  <strong>Instructions:</strong>
  <%= @exam.instructions %>
</p>

<p>
  <strong>Short name:</strong>
  <%= @exam.short_name %>
</p>

<p>
  <strong>Requires responsible:</strong>
  <%= @exam.requires_responsible %>
</p>

<%= link_to 'Edit', edit_exam_path(@exam) %> |
<%= link_to 'Back', exams_path %>

app/views/exams/smart.html.erb
<p id="notice"><%= notice %></p>

<div class="smart-container">
  <h2 class="title">Exames</h2>

  <% @exams.each do |exam| %>
    <div class="exam-card">
      <div class="exam-name"><%= exam.name.downcase %></div>
      <div class="area"><%= exam.short_name %> | <%= exam.area.downcase %></div>
      <div class="clear"></div>
    </div>
  <% end %>

  <h2 class="title">Preparos</h2>

  <% @instructions.each do |instruc| %>
    <div class="instruction-card">
      <div class="instruction-content">
        <%= instruc.content %>
        <div style="display:none">
        <b><%= instruc.instruction_type %></b> - 
        <b><%= instruc.id_at_alliar %></b>
        <b><%= instruc.id %></b>
        </div>
      </div>
    </div>
  <% end %>

  <h2 class="title">Contra indicações</h2>
  <span>Não existem.</span>
  <br />
  <br />
</div>